# Generated by Django 4.1.5 on 2023-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_alter_order_orderplaced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderPlaced",
            field=models.CharField(default="false", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderPlacedDate",
            field=models.CharField(default="Jan 20, 2023", max_length=50),
        ),
    ]
