# Generated by Django 4.1.5 on 2023-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_alter_order_orderplacedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderPlacedDate",
            field=models.CharField(default="Jan 24, 2023", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderPlacedtime",
            field=models.CharField(default="15:11 PM", max_length=50),
        ),
    ]
