# Generated by Django 4.1.5 on 2023-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0008_alter_order_orderplaced_alter_order_orderplacedtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="oldPrice",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="orderPlacedtime",
            field=models.CharField(default="15:36 PM", max_length=50),
        ),
    ]
