# Generated by Django 4.1.5 on 2023-01-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_product_offer_product_oldprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderPlacedtime",
            field=models.CharField(default="15:41 PM", max_length=50),
        ),
        migrations.AlterField(
            model_name="product", name="offer", field=models.IntegerField(null=True),
        ),
    ]
