# Generated by Django 4.1.5 on 2023-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_alter_order_orderplacedtime_alter_product_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderPlacedtime",
            field=models.CharField(default="16:10 PM", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="offer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="oldPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
